# Change these first
owner: ehsanfox # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Portfolio
    url: https://ehsan.js.org
    icon: https://ehsan.js.org/favicon.ico
    assignees:
      - EhsanFox

status-website:
  metaTags:
    - name: "theme-color"
      content: "#000000"
    - name: "description"
      content: "An automatic and dynamic generated page to show status and services created & hosted on Ehsan's Server and Github Pages"
    - name: "twitter:url"
      content: "https://ehsan.js.org/status/"
    - name: "twitter:title"
      content: "Ehsan's Uptime Page"
    - name: "twitter:description"
      content: "An automatic and dynamic generated page to show status and services created & hosted on Ehsan's Server and Github Pages"
    - name: "twitter:card"
      content: "summary"
  theme: ocean
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: ehsan.js.org
  # baseUrl: /status
  logoUrl: https://cdn.discordapp.com/attachments/557343148011945984/976740250640588800/Untitled-pfp.png
  name: EhsanFox's Uptime Page
  introTitle: "**Ehsan's Uptime Page** - aka BoyCode"
  introMessage: This page is [generated automaticly](https://github.com/EhsanFox/status) to show status and services created & hosted on [Ehsan](https://github.com/EhsanFox)'s Server and Github Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://ehsan.js.org
    - title: Discord
      href: https://discord.gg/7jgfP6j4Tc
i18n:
  footer: Made with 💖 By [Ehsan](https://github.com/EhsanFox) - Generated by Upptime
skipDescriptionUpdate: true
skipTopicsUpdate: true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
